language: cpp
sudo: required
dist: trusty # modern upx

env:
  matrix:
    - BATTLESHIP_PLATFORM='linux64'
    - BATTLESHIP_PLATFORM='windows32'
    - BATTLESHIP_PLATFORM='windows64'

before_install:
  - BATTLESHIP_TARGET="${BATTLESHIP_PLATFORM::${#BATTLESHIP_PLATFORM}-2}"
  - sudo apt-get update
  #- ./build/linux/requirements.sh
  - ./build/${BATTLESHIP_TARGET}/requirements.sh

install:
  - source ./build/${BATTLESHIP_TARGET}/build.sh

script:
  - echo "Nothing."

before_deploy:
  - source build-dir/package.sh

deploy:
  provider: releases
  api_key: "$GH_API_KEY"
  file: "$(ls battleship_*_*.exe)"
  skip_cleanup: true
  on:
    tags: true
