language: cpp
sudo: required
dist: trusty # modern upx

env:
  matrix:
    - PACKAGES='g++ cmake make libqt4-dev' CMAKE=cmake FILENAME_SUFFIX='linux64'
    - PACKAGES='mxe-i686-w64-mingw32.static-qt' CMAKE='/usr/lib/mxe/usr/bin/i686-w64-mingw32.static-cmake' FILENAME_SUFFIX='windows32'
    - PACKAGES='mxe-x86-64-w64-mingw32.static-qt' CMAKE='/usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-cmake' FILENAME_SUFFIX='windows64'

install:
  - echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mxeapt.list
  - sudo apt-key adv --keyserver x-hkp://keys.gnupg.net --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
  - sudo apt-get update
  - sudo apt-get install --yes upx-ucl $PACKAGES

script:
  - $CMAKE . -Bbuild-dir
  - cmake --build build-dir --config Release
  - source build-dir/rename_exe.sh

before_deploy:
  - strip $DEPLOY_FILE
  - upx -9 $DEPLOY_FILE
  - echo "$PATH"

deploy:
  provider: releases
  api_key: "$GH_API_KEY"
  file: "$(ls battleship_*_*.exe)"
  skip_cleanup: true
  on:
    tags: true
